//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaisDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class PaisDto : object
    {
        
        private string CodigoField;
        
        private string ContinenteField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Continente
        {
            get
            {
                return this.ContinenteField;
            }
            set
            {
                this.ContinenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaisService.IPaisService")]
    public interface IPaisService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaisService/ListarPaises", ReplyAction="http://tempuri.org/IPaisService/ListarPaisesResponse")]
        System.Threading.Tasks.Task<PaisService.PaisDto[]> ListarPaisesAsync(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaisService/ObtenerPais", ReplyAction="http://tempuri.org/IPaisService/ObtenerPaisResponse")]
        System.Threading.Tasks.Task<PaisService.PaisDto> ObtenerPaisAsync(string sessionToken, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaisService/CrearPais", ReplyAction="http://tempuri.org/IPaisService/CrearPaisResponse")]
        System.Threading.Tasks.Task CrearPaisAsync(string sessionToken, PaisService.PaisDto pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaisService/ActualizarPais", ReplyAction="http://tempuri.org/IPaisService/ActualizarPaisResponse")]
        System.Threading.Tasks.Task ActualizarPaisAsync(string sessionToken, PaisService.PaisDto pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaisService/EliminarPais", ReplyAction="http://tempuri.org/IPaisService/EliminarPaisResponse")]
        System.Threading.Tasks.Task EliminarPaisAsync(string sessionToken, string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPaisServiceChannel : PaisService.IPaisService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PaisServiceClient : System.ServiceModel.ClientBase<PaisService.IPaisService>, PaisService.IPaisService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaisServiceClient() : 
                base(PaisServiceClient.GetDefaultBinding(), PaisServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPaisService.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaisServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PaisServiceClient.GetBindingForEndpoint(endpointConfiguration), PaisServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaisServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaisServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaisServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaisServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PaisService.PaisDto[]> ListarPaisesAsync(string sessionToken)
        {
            return base.Channel.ListarPaisesAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<PaisService.PaisDto> ObtenerPaisAsync(string sessionToken, string codigo)
        {
            return base.Channel.ObtenerPaisAsync(sessionToken, codigo);
        }
        
        public System.Threading.Tasks.Task CrearPaisAsync(string sessionToken, PaisService.PaisDto pais)
        {
            return base.Channel.CrearPaisAsync(sessionToken, pais);
        }
        
        public System.Threading.Tasks.Task ActualizarPaisAsync(string sessionToken, PaisService.PaisDto pais)
        {
            return base.Channel.ActualizarPaisAsync(sessionToken, pais);
        }
        
        public System.Threading.Tasks.Task EliminarPaisAsync(string sessionToken, string codigo)
        {
            return base.Channel.EliminarPaisAsync(sessionToken, codigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaisService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                // result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaisService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/PaisService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaisServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPaisService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaisServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPaisService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPaisService,
        }
    }
}

