//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalidadService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalidadDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class LocalidadDto : object
    {
        
        private int CapacidadField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadioCodigoField;
        
        private decimal PrecioBaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadioCodigo
        {
            get
            {
                return this.EstadioCodigoField;
            }
            set
            {
                this.EstadioCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioBase
        {
            get
            {
                return this.PrecioBaseField;
            }
            set
            {
                this.PrecioBaseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalidadService.ILocalidadService")]
    public interface ILocalidadService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalidadService/ListarLocalidades", ReplyAction="http://tempuri.org/ILocalidadService/ListarLocalidadesResponse")]
        System.Threading.Tasks.Task<LocalidadService.LocalidadDto[]> ListarLocalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalidadService/ObtenerLocalidad", ReplyAction="http://tempuri.org/ILocalidadService/ObtenerLocalidadResponse")]
        System.Threading.Tasks.Task<LocalidadService.LocalidadDto> ObtenerLocalidadAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalidadService/CrearLocalidad", ReplyAction="http://tempuri.org/ILocalidadService/CrearLocalidadResponse")]
        System.Threading.Tasks.Task CrearLocalidadAsync(LocalidadService.LocalidadDto localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalidadService/ActualizarLocalidad", ReplyAction="http://tempuri.org/ILocalidadService/ActualizarLocalidadResponse")]
        System.Threading.Tasks.Task ActualizarLocalidadAsync(LocalidadService.LocalidadDto localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalidadService/EliminarLocalidad", ReplyAction="http://tempuri.org/ILocalidadService/EliminarLocalidadResponse")]
        System.Threading.Tasks.Task EliminarLocalidadAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ILocalidadServiceChannel : LocalidadService.ILocalidadService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LocalidadServiceClient : System.ServiceModel.ClientBase<LocalidadService.ILocalidadService>, LocalidadService.ILocalidadService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LocalidadServiceClient() : 
                base(LocalidadServiceClient.GetDefaultBinding(), LocalidadServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILocalidadService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocalidadServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LocalidadServiceClient.GetBindingForEndpoint(endpointConfiguration), LocalidadServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocalidadServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LocalidadServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocalidadServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LocalidadServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocalidadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LocalidadService.LocalidadDto[]> ListarLocalidadesAsync()
        {
            return base.Channel.ListarLocalidadesAsync();
        }
        
        public System.Threading.Tasks.Task<LocalidadService.LocalidadDto> ObtenerLocalidadAsync(string codigo)
        {
            return base.Channel.ObtenerLocalidadAsync(codigo);
        }
        
        public System.Threading.Tasks.Task CrearLocalidadAsync(LocalidadService.LocalidadDto localidad)
        {
            return base.Channel.CrearLocalidadAsync(localidad);
        }
        
        public System.Threading.Tasks.Task ActualizarLocalidadAsync(LocalidadService.LocalidadDto localidad)
        {
            return base.Channel.ActualizarLocalidadAsync(localidad);
        }
        
        public System.Threading.Tasks.Task EliminarLocalidadAsync(string codigo)
        {
            return base.Channel.EliminarLocalidadAsync(codigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocalidadService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocalidadService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/LocalidadService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LocalidadServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILocalidadService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LocalidadServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILocalidadService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILocalidadService,
        }
    }
}

