//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadioService
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadioDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class EstadioDto : object
    {
        private int CapacidadTotalField;
        private string CiudadField;
        private string CodigoField;
        private string NombreField;
        private string PaisCodigoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CapacidadTotal
        {
            get { return this.CapacidadTotalField; }
            set { this.CapacidadTotalField = value; }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get { return this.CiudadField; }
            set { this.CiudadField = value; }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get { return this.CodigoField; }
            set { this.CodigoField = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get { return this.NombreField; }
            set { this.NombreField = value; }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisCodigo
        {
            get { return this.PaisCodigoField; }
            set { this.PaisCodigoField = value; }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadioService.IEstadioService")]
    public interface IEstadioService
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadioService/ListarEstadios", ReplyAction="http://tempuri.org/IEstadioService/ListarEstadiosResponse")]
        System.Threading.Tasks.Task<EstadioService.EstadioDto[]> ListarEstadiosAsync(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadioService/ObtenerEstadio", ReplyAction="http://tempuri.org/IEstadioService/ObtenerEstadioResponse")]
        System.Threading.Tasks.Task<EstadioService.EstadioDto> ObtenerEstadioAsync(string sessionToken, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadioService/CrearEstadio", ReplyAction="http://tempuri.org/IEstadioService/CrearEstadioResponse")]
        System.Threading.Tasks.Task CrearEstadioAsync(string sessionToken, EstadioService.EstadioDto estadio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadioService/ActualizarEstadio", ReplyAction="http://tempuri.org/IEstadioService/ActualizarEstadioResponse")]
        System.Threading.Tasks.Task ActualizarEstadioAsync(string sessionToken, EstadioService.EstadioDto estadio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadioService/EliminarEstadio", ReplyAction="http://tempuri.org/IEstadioService/EliminarEstadioResponse")]
        System.Threading.Tasks.Task EliminarEstadioAsync(string sessionToken, string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IEstadioServiceChannel : EstadioService.IEstadioService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EstadioServiceClient : System.ServiceModel.ClientBase<EstadioService.IEstadioService>, EstadioService.IEstadioService
    {
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstadioServiceClient() : 
                base(EstadioServiceClient.GetDefaultBinding(), EstadioServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEstadioService.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstadioServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EstadioServiceClient.GetBindingForEndpoint(endpointConfiguration), EstadioServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public System.Threading.Tasks.Task<EstadioService.EstadioDto[]> ListarEstadiosAsync(string sessionToken)
        {
            return base.Channel.ListarEstadiosAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<EstadioService.EstadioDto> ObtenerEstadioAsync(string sessionToken, string codigo)
        {
            return base.Channel.ObtenerEstadioAsync(sessionToken, codigo);
        }
        
        public System.Threading.Tasks.Task CrearEstadioAsync(string sessionToken, EstadioService.EstadioDto estadio)
        {
            return base.Channel.CrearEstadioAsync(sessionToken, estadio);
        }
        
        public System.Threading.Tasks.Task ActualizarEstadioAsync(string sessionToken, EstadioService.EstadioDto estadio)
        {
            return base.Channel.ActualizarEstadioAsync(sessionToken, estadio);
        }
        
        public System.Threading.Tasks.Task EliminarEstadioAsync(string sessionToken, string codigo)
        {
            return base.Channel.EliminarEstadioAsync(sessionToken, codigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEstadioService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                // result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEstadioService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/EstadioService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EstadioServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEstadioService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EstadioServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEstadioService);
        }
        
        public enum EndpointConfiguration
        {
            BasicHttpBinding_IEstadioService,
        }
    }
}

