//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenLocalidadDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class ResumenLocalidadDto : object
    {
        
        private int BoletosVendidosField;
        
        private string CodigoLocalidadField;
        
        private string DescripcionLocalidadField;
        
        private decimal TotalRecaudadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BoletosVendidos
        {
            get
            {
                return this.BoletosVendidosField;
            }
            set
            {
                this.BoletosVendidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLocalidad
        {
            get
            {
                return this.CodigoLocalidadField;
            }
            set
            {
                this.CodigoLocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLocalidad
        {
            get
            {
                return this.DescripcionLocalidadField;
            }
            set
            {
                this.DescripcionLocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalRecaudado
        {
            get
            {
                return this.TotalRecaudadoField;
            }
            set
            {
                this.TotalRecaudadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenClienteDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class ResumenClienteDto : object
    {
        
        private string AsientoField;
        
        private System.DateTime FechaField;
        
        private string LocalidadField;
        
        private string MetodoPagoField;
        
        private string NumeroFacturaField;
        
        private string PartidoField;
        
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asiento
        {
            get
            {
                return this.AsientoField;
            }
            set
            {
                this.AsientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoPago
        {
            get
            {
                return this.MetodoPagoField;
            }
            set
            {
                this.MetodoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partido
        {
            get
            {
                return this.PartidoField;
            }
            set
            {
                this.PartidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReporteService.IReporteService")]
    public interface IReporteService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteService/ResumenVentasPorPartido", ReplyAction="http://tempuri.org/IReporteService/ResumenVentasPorPartidoResponse")]
        System.Threading.Tasks.Task<ReporteService.ResumenLocalidadDto[]> ResumenVentasPorPartidoAsync(string sessionToken, string codigoPartido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteService/ResumenVentasPorCliente", ReplyAction="http://tempuri.org/IReporteService/ResumenVentasPorClienteResponse")]
        System.Threading.Tasks.Task<ReporteService.ResumenClienteDto[]> ResumenVentasPorClienteAsync(string sessionToken, string cedulaCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IReporteServiceChannel : ReporteService.IReporteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ReporteServiceClient : System.ServiceModel.ClientBase<ReporteService.IReporteService>, ReporteService.IReporteService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReporteServiceClient() : 
                base(ReporteServiceClient.GetDefaultBinding(), ReporteServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReporteService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReporteServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReporteServiceClient.GetBindingForEndpoint(endpointConfiguration), ReporteServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReporteServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReporteServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReporteServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReporteServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReporteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReporteService.ResumenLocalidadDto[]> ResumenVentasPorPartidoAsync(string sessionToken, string codigoPartido)
        {
            return base.Channel.ResumenVentasPorPartidoAsync(sessionToken, codigoPartido);
        }
        
        public System.Threading.Tasks.Task<ReporteService.ResumenClienteDto[]> ResumenVentasPorClienteAsync(string sessionToken, string cedulaCliente)
        {
            return base.Channel.ResumenVentasPorClienteAsync(sessionToken, cedulaCliente);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReporteService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReporteService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/ReporteService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReporteServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReporteService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReporteServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReporteService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReporteService,
        }
    }
}

