//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class ClienteDto : object
    {
        
        private string ApellidoField;
        
        private string CedulaField;
        
        private string EmailField;
        
        private System.DateTime FechaNacimientoField;
        
        private string GeneroField;
        
        private string NombreField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IClienteService")]
    public interface IClienteService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarClientes", ReplyAction="http://tempuri.org/IClienteService/ListarClientesResponse")]
        System.Threading.Tasks.Task<ClienteService.ClienteDto[]> ListarClientesAsync(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteService/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<ClienteService.ClienteDto> ObtenerClienteAsync(string sessionToken, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CrearCliente", ReplyAction="http://tempuri.org/IClienteService/CrearClienteResponse")]
        System.Threading.Tasks.Task CrearClienteAsync(string sessionToken, ClienteService.ClienteDto cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ActualizarCliente", ReplyAction="http://tempuri.org/IClienteService/ActualizarClienteResponse")]
        System.Threading.Tasks.Task ActualizarClienteAsync(string sessionToken, ClienteService.ClienteDto cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/EliminarCliente", ReplyAction="http://tempuri.org/IClienteService/EliminarClienteResponse")]
        System.Threading.Tasks.Task EliminarClienteAsync(string sessionToken, string cedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IClienteServiceChannel : ClienteService.IClienteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<ClienteService.IClienteService>, ClienteService.IClienteService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClienteServiceClient() : 
                base(ClienteServiceClient.GetDefaultBinding(), ClienteServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IClienteService.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), ClienteServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            // ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ClienteService.ClienteDto[]> ListarClientesAsync(string sessionToken)
        {
            return base.Channel.ListarClientesAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<ClienteService.ClienteDto> ObtenerClienteAsync(string sessionToken, string cedula)
        {
            return base.Channel.ObtenerClienteAsync(sessionToken, cedula);
        }
        
        public System.Threading.Tasks.Task CrearClienteAsync(string sessionToken, ClienteService.ClienteDto cliente)
        {
            return base.Channel.CrearClienteAsync(sessionToken, cliente);
        }
        
        public System.Threading.Tasks.Task ActualizarClienteAsync(string sessionToken, ClienteService.ClienteDto cliente)
        {
            return base.Channel.ActualizarClienteAsync(sessionToken, cliente);
        }
        
        public System.Threading.Tasks.Task EliminarClienteAsync(string sessionToken, string cedula)
        {
            return base.Channel.EliminarClienteAsync(sessionToken, cedula);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IClienteService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                // result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IClienteService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/ClienteService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClienteServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IClienteService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClienteServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IClienteService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IClienteService,
        }
    }
}

