//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartidoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidoDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class PartidoDto : object
    {
        
        private string CodigoField;
        
        private string EquipoLocalField;
        
        private string EquipoVisitanteField;
        
        private string EstadioCodigoField;
        
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoLocal
        {
            get
            {
                return this.EquipoLocalField;
            }
            set
            {
                this.EquipoLocalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoVisitante
        {
            get
            {
                return this.EquipoVisitanteField;
            }
            set
            {
                this.EquipoVisitanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadioCodigo
        {
            get
            {
                return this.EstadioCodigoField;
            }
            set
            {
                this.EstadioCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartidoService.IPartidoService")]
    public interface IPartidoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidoService/ListarPartidos", ReplyAction="http://tempuri.org/IPartidoService/ListarPartidosResponse")]
        System.Threading.Tasks.Task<PartidoService.PartidoDto[]> ListarPartidosAsync(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidoService/ObtenerPartido", ReplyAction="http://tempuri.org/IPartidoService/ObtenerPartidoResponse")]
        System.Threading.Tasks.Task<PartidoService.PartidoDto> ObtenerPartidoAsync(string sessionToken, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidoService/CrearPartido", ReplyAction="http://tempuri.org/IPartidoService/CrearPartidoResponse")]
        System.Threading.Tasks.Task CrearPartidoAsync(string sessionToken, PartidoService.PartidoDto partido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidoService/ActualizarPartido", ReplyAction="http://tempuri.org/IPartidoService/ActualizarPartidoResponse")]
        System.Threading.Tasks.Task ActualizarPartidoAsync(string sessionToken, PartidoService.PartidoDto partido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidoService/EliminarPartido", ReplyAction="http://tempuri.org/IPartidoService/EliminarPartidoResponse")]
        System.Threading.Tasks.Task EliminarPartidoAsync(string sessionToken, string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPartidoServiceChannel : PartidoService.IPartidoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PartidoServiceClient : System.ServiceModel.ClientBase<PartidoService.IPartidoService>, PartidoService.IPartidoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PartidoServiceClient() : 
                base(PartidoServiceClient.GetDefaultBinding(), PartidoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPartidoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PartidoServiceClient.GetBindingForEndpoint(endpointConfiguration), PartidoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PartidoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PartidoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PartidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PartidoService.PartidoDto[]> ListarPartidosAsync(string sessionToken)
        {
            return base.Channel.ListarPartidosAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<PartidoService.PartidoDto> ObtenerPartidoAsync(string sessionToken, string codigo)
        {
            return base.Channel.ObtenerPartidoAsync(sessionToken, codigo);
        }
        
        public System.Threading.Tasks.Task CrearPartidoAsync(string sessionToken, PartidoService.PartidoDto partido)
        {
            return base.Channel.CrearPartidoAsync(sessionToken, partido);
        }
        
        public System.Threading.Tasks.Task ActualizarPartidoAsync(string sessionToken, PartidoService.PartidoDto partido)
        {
            return base.Channel.ActualizarPartidoAsync(sessionToken, partido);
        }
        
        public System.Threading.Tasks.Task EliminarPartidoAsync(string sessionToken, string codigo)
        {
            return base.Channel.EliminarPartidoAsync(sessionToken, codigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPartidoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPartidoService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/PartidoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PartidoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPartidoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PartidoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPartidoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPartidoService,
        }
    }
}


