//------------------------------------------------------------------------------
// <auto-generated>
//     Este c�digo fue generado por una herramienta.
//
//     Los cambios en este archivo podr�an causar un comportamiento incorrecto y se perder�n si
//     se vuelve a generar el c�digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompraService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmortizacionDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class AmortizacionDto : object
    {
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCuota { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InteresPagado { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CapitalPagado { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago { get; set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraResponse", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class CompraResponse : object
    {
        
        private bool ExitosoField;
        
        private string MensajeField;
        
        private string NumeroFacturaField;

        private CompraService.AmortizacionDto[] AmortizacionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompraService.AmortizacionDto[] Amortizaciones
        {
            get
            {
                return this.AmortizacionesField;
            }
            set
            {
                this.AmortizacionesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompraService.ICompraService")]
    public interface ICompraService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompraService/ComprarEnEfectivo", ReplyAction="http://tempuri.org/ICompraService/ComprarEnEfectivoResponse")]
        System.Threading.Tasks.Task<CompraService.CompraResponse> ComprarEnEfectivoAsync(string sessionToken, string[] codigosAsiento, string clienteCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompraService/ComprarACredito", ReplyAction="http://tempuri.org/ICompraService/ComprarACreditoResponse")]
        System.Threading.Tasks.Task<CompraService.CompraResponse> ComprarACreditoAsync(string sessionToken, string[] codigosAsiento, string clienteCedula, int plazoMeses);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICompraServiceChannel : CompraService.ICompraService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CompraServiceClient : System.ServiceModel.ClientBase<CompraService.ICompraService>, CompraService.ICompraService
    {
        
        /// <summary>
        /// Implemente este m�todo parcial para configurar el punto de conexi�n de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexi�n para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompraServiceClient() : 
                base(CompraServiceClient.GetDefaultBinding(), CompraServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICompraService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CompraServiceClient.GetBindingForEndpoint(endpointConfiguration), CompraServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompraServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompraServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CompraService.CompraResponse> ComprarEnEfectivoAsync(string sessionToken, string[] codigosAsiento, string clienteCedula)
        {
            return base.Channel.ComprarEnEfectivoAsync(sessionToken, codigosAsiento, clienteCedula);
        }
        
        public System.Threading.Tasks.Task<CompraService.CompraResponse> ComprarACreditoAsync(string sessionToken, string[] codigosAsiento, string clienteCedula, int plazoMeses)
        {
            return base.Channel.ComprarACreditoAsync(sessionToken, codigosAsiento, clienteCedula, plazoMeses);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompraService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexi�n con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompraService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.137:9099/CompraService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexi�n con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CompraServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICompraService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CompraServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICompraService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICompraService,
        }
    }
}




