//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaResponse", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class FacturaResponse : object
    {
        
        private string ClienteCedulaField;
        
        private decimal DescuentoField;
        
        private System.DateTime FechaField;
        
        private FacturaService.FacturaItemDto[] ItemsField;
        
        private decimal IvaField;
        
        private string MetodoPagoField;
        
        private string NumeroField;
        
        private decimal SubtotalField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteCedula
        {
            get
            {
                return this.ClienteCedulaField;
            }
            set
            {
                this.ClienteCedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Descuento
        {
            get
            {
                return this.DescuentoField;
            }
            set
            {
                this.DescuentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturaService.FacturaItemDto[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Iva
        {
            get
            {
                return this.IvaField;
            }
            set
            {
                this.IvaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoPago
        {
            get
            {
                return this.MetodoPagoField;
            }
            set
            {
                this.MetodoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaItemDto", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.TicketPremium.Contracts")]
    public partial class FacturaItemDto : object
    {
        
        private string CodigoAsientoField;
        
        private string LocalidadField;
        
        private string PartidoField;
        
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAsiento
        {
            get
            {
                return this.CodigoAsientoField;
            }
            set
            {
                this.CodigoAsientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partido
        {
            get
            {
                return this.PartidoField;
            }
            set
            {
                this.PartidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacturaService.IFacturaService")]
    public interface IFacturaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturaService/CalcularFactura", ReplyAction="http://tempuri.org/IFacturaService/CalcularFacturaResponse")]
        System.Threading.Tasks.Task<FacturaService.FacturaResponse> CalcularFacturaAsync(string[] codigosAsiento, bool esEfectivo, string clienteCedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFacturaServiceChannel : FacturaService.IFacturaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FacturaServiceClient : System.ServiceModel.ClientBase<FacturaService.IFacturaService>, FacturaService.IFacturaService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FacturaServiceClient() : 
                base(FacturaServiceClient.GetDefaultBinding(), FacturaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFacturaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FacturaServiceClient.GetBindingForEndpoint(endpointConfiguration), FacturaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FacturaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FacturaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FacturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FacturaService.FacturaResponse> CalcularFacturaAsync(string[] codigosAsiento, bool esEfectivo, string clienteCedula)
        {
            return base.Channel.CalcularFacturaAsync(codigosAsiento, esEfectivo, clienteCedula);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacturaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFacturaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9099/FacturaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FacturaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFacturaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FacturaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFacturaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFacturaService,
        }
    }
}
